name: Build Linux

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install GLU
        run: apt-get install libmesa-dev
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.8.0
        with:
          version: '5.15.1'
      - run: qmake QuteScoop-unix.pro
      - run: make
      - run: make install
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
